// FitSync Authentication Service (Dual Mode: Supabase or Local Mock Fallback)

import { supabase, isSupabaseConfigured } from '../lib/supabase';
import { getFromMockDb, saveToMockDb } from './mockDb';
import type { UserProfile, OnlineStatus, Friend, LeaderboardEntry } from '../types';
import { emailSchema, passwordSchema, usernameSchema } from '../utils/validation';

export interface UserSession {
  user: {
    id: string;
    email: string;
  } | null;
  profile: UserProfile | null;
}

const SESSION_KEY = 'fs_session';

export const AuthService = {
  // 1. Sign Up
  async signUp(email: string, password: string, username: string, fullName: string): Promise<{ data: UserSession; error: any }> {
    try {
      // Zod Validation
      emailSchema.parse(email);
      passwordSchema.parse(password);
      usernameSchema.parse(username);
    } catch (validationError: any) {
      return { data: { user: null, profile: null }, error: validationError.errors?.[0]?.message || 'Validation error.' };
    }

    if (isSupabaseConfigured) {
      try {
        const { data, error } = await supabase.auth.signUp({
          email,
          password,
          options: {
            data: {
              username,
              full_name: fullName,
            }
          }
        });
        if (error) throw error;
        return {
          data: {
            user: data.user ? { id: data.user.id, email: data.user.email || '' } : null,
            profile: null // Generated by database trigger
          },
          error: null
        };
      } catch (err: any) {
        return { data: { user: null, profile: null }, error: err.message || err };
      }
    } else {
      // Mock local signup
      const profiles = getFromMockDb<UserProfile>('profiles');
      const lowerUsername = username.toLowerCase();
      
      if (profiles.some(p => p.username.toLowerCase() === lowerUsername)) {
        return { data: { user: null, profile: null }, error: 'Username is already taken.' };
      }
      
      const newUserId = 'user-' + Math.random().toString(36).substr(2, 9);
      const fitsyncId = 'FS-' + Math.floor(10000000 + Math.random() * 90000000).toString();
      
      const newProfile: UserProfile = {
        id: newUserId,
        user_id: newUserId,
        username,
        fitsync_id: fitsyncId,
        full_name: fullName,
        avatar_url: `https://api.dicebear.com/7.x/adventurer/svg?seed=${username}`,
        age: 25,
        gender: 'Not Specified',
        height: 175,
        weight: 70,
        fitness_goal: 'Stay Healthy',
        bio: 'Just joined FitSync! Ready to track and compete.',
        location: 'Earth',
        created_at: new Date().toISOString()
      };

      profiles.push(newProfile);
      saveToMockDb('profiles', profiles);

      // Save online status
      const status = getFromMockDb<OnlineStatus>('online_status');
      status.push({
        profile_id: newUserId,
        is_online: true,
        last_seen: new Date().toISOString()
      });
      saveToMockDb('online_status', status);

      // Add default friends for social features
      const friends = getFromMockDb<Friend>('friends');
      friends.push(
        { id: `f-${newUserId}-alex`, user1: newUserId, user2: 'user-alex', created_at: new Date().toISOString() },
        { id: `f-${newUserId}-sarah`, user1: newUserId, user2: 'user-sarah', created_at: new Date().toISOString() }
      );
      saveToMockDb('friends', friends);

      // Add default leaderboard standings
      const leaderboard = getFromMockDb<LeaderboardEntry>('leaderboards');
      leaderboard.push(
        { id: `l-${newUserId}-d`, user_id: newUserId, score: 0, period: 'daily', created_at: new Date().toISOString() },
        { id: `l-${newUserId}-w`, user_id: newUserId, score: 0, period: 'weekly', created_at: new Date().toISOString() },
        { id: `l-${newUserId}-m`, user_id: newUserId, score: 0, period: 'monthly', created_at: new Date().toISOString() }
      );
      saveToMockDb('leaderboards', leaderboard);

      const session: UserSession = {
        user: { id: newUserId, email },
        profile: newProfile
      };

      localStorage.setItem(SESSION_KEY, JSON.stringify(session));
      return { data: session, error: null };
    }
  },

  // 2. Sign In
  async signIn(email: string, password?: string): Promise<{ data: UserSession; error: any }> {
    try {
      emailSchema.parse(email);
      if (password !== undefined) passwordSchema.parse(password);
    } catch (validationError: any) {
      return { data: { user: null, profile: null }, error: validationError.errors?.[0]?.message || 'Validation error.' };
    }

    if (isSupabaseConfigured) {
      try {
        const { data, error } = await supabase.auth.signInWithPassword({
          email,
          password: password || 'temp_password_123!'
        });
        if (error) throw error;
        
        // Fetch Profile details
        const { data: profile } = await supabase
          .from('profiles')
          .select('*')
          .eq('id', data.user?.id)
          .single();

        return {
          data: {
            user: data.user ? { id: data.user.id, email: data.user.email || '' } : null,
            profile: profile as unknown as UserProfile
          },
          error: null
        };
      } catch (err: any) {
        return { data: { user: null, profile: null }, error: err.message || err };
      }
    } else {
      // Mock local signin
      const profiles = getFromMockDb<UserProfile>('profiles');
      let profile = profiles.find(p => p.username === email.split('@')[0]) || profiles[0];
      
      if (!profile) {
        return { data: { user: null, profile: null }, error: 'User profile not found.' };
      }

      const session: UserSession = {
        user: { id: profile.id, email },
        profile
      };

      // Set online
      const status = getFromMockDb<OnlineStatus>('online_status');
      const userStatus = status.find(s => s.profile_id === profile.id);
      if (userStatus) {
        userStatus.is_online = true;
        userStatus.last_seen = new Date().toISOString();
        saveToMockDb('online_status', status);
      }

      localStorage.setItem(SESSION_KEY, JSON.stringify(session));
      return { data: session, error: null };
    }
  },

  // 3. Google OAuth Login
  async signInWithGoogle(): Promise<{ error: any }> {
    if (isSupabaseConfigured) {
      const { error } = await supabase.auth.signInWithOAuth({
        provider: 'google',
        options: {
          redirectTo: window.location.origin + '/dashboard'
        }
      });
      return { error };
    } else {
      console.log('Simulating Google login flow...');
      return { error: null };
    }
  },

  // 4. Session Persistence & Auto Login
  async getSession(): Promise<UserSession | null> {
    if (isSupabaseConfigured) {
      try {
        const { data: { session } } = await supabase.auth.getSession();
        if (!session) return null;

        const { data: profile } = await supabase
          .from('profiles')
          .select('*')
          .eq('id', session.user.id)
          .single();

        return {
          user: { id: session.user.id, email: session.user.email || '' },
          profile: profile as unknown as UserProfile
        };
      } catch {
        return null;
      }
    } else {
      const sessionData = localStorage.getItem(SESSION_KEY);
      if (!sessionData) return null;
      
      const parsed: UserSession = JSON.parse(sessionData);
      if (parsed.profile) {
        const profiles = getFromMockDb<UserProfile>('profiles');
        const refreshedProfile = profiles.find(p => p.id === parsed.profile?.id);
        if (refreshedProfile) {
          parsed.profile = refreshedProfile;
          localStorage.setItem(SESSION_KEY, JSON.stringify(parsed));
        }
      }
      return parsed;
    }
  },

  // 5. Sign Out
  async signOut(userId?: string): Promise<{ error: any }> {
    if (isSupabaseConfigured) {
      const { error } = await supabase.auth.signOut();
      return { error };
    } else {
      if (userId) {
        const status = getFromMockDb<OnlineStatus>('online_status');
        const userStatus = status.find(s => s.profile_id === userId);
        if (userStatus) {
          userStatus.is_online = false;
          userStatus.last_seen = new Date().toISOString();
          saveToMockDb('online_status', status);
        }
      }
      localStorage.removeItem(SESSION_KEY);
      return { error: null };
    }
  },

  // 6. Forgot Password
  async forgotPassword(email: string): Promise<{ error: any }> {
    try {
      emailSchema.parse(email);
    } catch (valErr: any) {
      return { error: valErr.errors?.[0]?.message || 'Invalid email.' };
    }

    if (isSupabaseConfigured) {
      const { error } = await supabase.auth.resetPasswordForEmail(email, {
        redirectTo: window.location.origin + '/reset-password'
      });
      return { error };
    } else {
      console.log(`Password reset link requested for ${email}`);
      return { error: null };
    }
  },

  // 7. Reset Password
  async resetPassword(password: string): Promise<{ error: any }> {
    try {
      passwordSchema.parse(password);
    } catch (valErr: any) {
      return { error: valErr.errors?.[0]?.message || 'Invalid password.' };
    }

    if (isSupabaseConfigured) {
      const { error } = await supabase.auth.updateUser({ password });
      return { error };
    } else {
      console.log('Password successfully reset in mock database.');
      return { error: null };
    }
  }
};
